---
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'    
      - match_re:
          severity: '^(none|warning|critical)$'
        receiver: 
    receivers:
      - name: 'null'
      - name: 
        slack_configs:
          - api_url: 
            channel: '#aks-prometheus'
